###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Computador",
    "price": 3.000
}
###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Notebook",
    "price": 4.000
}